import re
inp = open("grammer.txt", "r").read()
inp = str(inp)
a=[('LSHIFTEQOP', "'<<='"), ('RSHIFTEQOP', "'>>='"), ('LEFTQOP', "'<<='"), ('RIGHTQOP', "'>>='"), ('ARROWSTAR', "'_>*'"), ('BOREQOP', "'|='"), ('OROP', "'||'"), ('ANDOP', "'&&'"), ('PLUSEQOP', "'+='"), ('MODEQOP', "'%='"), ('MINUSEQOP', "'_='"), ('MULTEQOP', "'*='"), ('DIVEQOP', "'/='"), ('BANDEQOP', "'&='"), ('B_I_OR', "'|='"), ('B_E_OR', "'^='"), ('XOREQOP', "'^='"), ('DPLUSOP', "'++'"), ('DMINUSOP', "'__'"), ('EXPOP', "'**'"), ('LSHIFT', "'<<'"), ('RSHIFT', "'>>'"), ('LEFTSHIFT', "'<<'"), ('RIGHTLIFT', "'>>'"), ('CONDTIONAL', "'?:'"), ('MODQOP', "'%='"), ('EQCOMP', "'=='"), ('NEQCOMP', "'!='"), ('GTECOMP', "'>='"), ('LTECOMP', "'<='"), ('DOUBLECOLON', "'::'"), ('ARROW', "'_>'"), ('DOTSTAR', "'.*'"), ('PLUSOP', "'+'"), ('MINUSOP', "'_'"), ('DIVOP', "'/'"), ('MULTOP', "'*'"), ('MODOP', "'%'"), ('XOROP', "'^'"), ('BANDOP', "'&'"), ('BNOP', "'~'"), ('GTCOMP', "'>'"), ('LTCOMP', "'<'"), ('LRPAREN', "'('"), ('RRPAREN', "')'"), ('LCPAREN', "'{'"), ('RCPAREN', "'}'"), ('LSPAREN', "'['"), ('RSPAREN', "']'"), ('DOT', "'.'"), ('SEMICOLON', "';'"), ('NOTSYM', "'!'"), ('QUESMARK', "'?'")]
for each in a:
    inp=inp.replace(" "+each[1] ," "+each[0])
    
keywords = {
    'and':'AND',
    'and_eq':'AND_EQ',
    'asm':'ASM',
    'auto':'AUTO',
    'bitand':'BITAND',
    'bitor':'BITOR',
    'bool':'BOOL',
    'break':'BREAK',
    'case':'CASE',
    'catch':'CATCH',
    'char':'CHAR',
    'char8_t':'CHAR8_T',
    'char16_t':'CHAR16_T',
    'char32_t':'CHAR32_T',
    'class':'CLASS',
    'compl':'COMPL',
    'const':'CONST',
    'continue':'CONTINUE',
    'default':'DEFAULT',
    'delete':'DELETE',
    'do':'DO',
    'double':'DOUBLE',
    'else':'ELSE',
    'enum':'ENUM',
    'extern':'EXTERN',
    'false':'FALSE',
    'float':'FLOAT',
    'for':'FOR',
    'goto':'GOTO',
    'if':'IF',
    'inline':'INLINE',
    'int':'INT',
    'long':'LONG',
    'namespace':'NAMESPACE',
    'new':'NEW',
    'not':'NOT',
    'not_eq':'NOT_EQ',
    'nullptr':'NULLPTR',
    'or':'OR',
    'or_eq':'OR_EQ',
    'private':'PRIVATE',
    'protected':'PROTECTED',
    'public':'PUBLIC',
    'return':'RETURN',
    'short':'SHORT',
    'signed':'SIGNED',
    'sizeof':'SIZEOF',
    'static':'STATIC',
    'std' : 'STD',
    'switch':'SWITCH',
    'this':'THIS',
    'throw':'THROW',
    'true':'TRUE',
    'try':'TRY',
    'typedef':'TYPEDEF',
    'union':'UNION',
    'unsigned':'UNSIGNED',
    'using' : 'USING',
    'virtual':'VIRTUAL',
    'void':'VOID',
    'volatile':'VOLATILE',
    'while':'WHILE',
    'xor':'XOR',
    'xor_eq':'XOR_EQ',
}
for k,v in keywords.items():
    inp=inp.replace(" "+k+" " ," "+v+" ")
print(inp)