#!/bin/bash
for i in $(ls ../tests);
do
	cat ../tests/$i|grep -v "cout">temp
	cat temp|grep -v "cin">temp1
	x=$(python3 parser.py 0 temp1 )
	f=${x/Error/er}
	if [[ "$f" != "$x" ]];
	then
		echo "----------------------------------"
		echo "Test ../tests/$i"
		echo "Error :"
		echo -e $x
	else
		echo "----------------------------------"
		echo "Test ../tests/$i passed"
	fi
done
