#!/bin/bash
for i in $(ls ../tests);
do
	x=$(python3 parser.py 0 ../tests/$i d)
	f=${x/error/er}
	if [[ "$f" != "$x" ]];
	then
		echo "----------------------------------"
		echo "Test ../tests/$i"
		echo "Error :"
		echo "$x"
	else
		echo "----------------------------------"
		echo "Test ../tests/$i passed"
	fi
done
