#!/bin/bash
x=$(python3.7 parser.py 0 ../tests/$1.cpp c)
dot -Tps dot.gz -o out.ps
if [[ "$2" == "o" ]];then
	xdg-open out.ps
elif [[ "$2" == "d" ]];then
	python3.7 parser.py 1 ../tests/$1.cpp c
else
	echo $x
fi
